### ISSUE TITLE
Hangs sometimes

### ISSUE THREAD

**Issue by dhcgn** [deadlydog/Invoke-MsBuild#13] opened 2016-11-09 19:20 UTC
Sometimes (sadly not reproduktiv) `Invoke-MsBuild` hangs, so I need to use `Start-Job` with `Timeout`.

```
$slns = gci 'C:\DEV' -Recurse -Filter *.sln
foreach ($sln in $slns)
{
    $result = $null;
    $job = Start-Job -InitializationScript { Import-Module -Name 'Invoke-MsBuild.psm1'} -ScriptBlock {
         Invoke-MsBuild -Path $args[0]  -BuildLogDirectoryPath $args[1]  -MsBuildParameters "/target:Clean;Build" -WarningAction silentlyContinue
    } -ArgumentList  @($sln.FullName, $logFolder) | Wait-Job -Timeout 100

    $result = $job | Receive-Job 

    if ($result.BuildSucceeded)
    {
        Write-Host ("Build was OK ({0})" -f $sln.FullName) -ForegroundColor Green
    }else
    {
        Write-Host ("Build was NOT OK ({0})" -f $sln.FullName) -ForegroundColor Red
        $errorOccur = $true;
    }
}
```

`Project.sln.msbuild.log` and `Project.sln.msbulid.errors.log` are not deleted.

**Comment by deadlydog** [comment] 2016-12-04 19:37
Sorry it took so long for me to see this. Apparently I didn't have my notifications configured properly in GitHub :(

Thanks for posting your workaround. I'm sure it will be helpful for others!

I think this bug is a duplicate of #11, so I'm going to close it for now. If you feel otherwise though just let me know.

**Closed by deadlydog** 2016-12-04 19:37 UTC
Labels: bug, duplicate
